version: '3'
services:
  QuickPasteRedux:
    container_name: Web
    build: .
    ports:
      - "8086:8080"
    volumes:
      - files:/home/code/files
    environment:
    restart: unless-stopped
volumes:
  files:
