version: '3'
services:
  web:
    build: .
    ports:
      - "${PORT}:8080"
    volumes:
      - .:/home/code/
    environment:
      - ENV=${ENV}
      - STARTLETTE_CONFIG=.env-${ENV}
      - HYPERCORN_CONFIG=Hypercorn-${ENV}.toml