version: '3'
services:
  quickpasteredux:
    container_name: Web
    build: .
    ports:
      - "8086:8080"
    volumes:
      - files:/home/code/files
    environment:
      DEBUG: "false"
      DATABASE_URL: <TODO>
    restart: unless-stopped
volumes:
  files:
